### ISSUE TITLE
Lose focus problem (Vue.js)

### ISSUE THREAD

**Issue by bifan** [gwenf/curriculum-app#6]
Lose focus when you input, because variable exists in both "v-model" and ":key"
[repeat problem on codepen.io](https://codepen.io/Jon_codePen/pen/abOzOyy)

But I can't find the reason.

(English is not my first language, I hope I've made myself clear.)

**Comment by bifan** [comment]
Finally, I figured it out.
Variable exists in both `v-model` and `:key`
We changing `:key` every typing.
`Vue` will remove `<input>` then add new one, that's why lose focus.

![vue](https://user-images.githubusercontent.com/2929293/77235934-fc75eb00-6bf4-11ea-9617-8b95b9aa5cb7.gif)

https://codepen.io/Jon_codePen/pen/abOzOyy

**Comment by gwenf** [comment]
@bifan thank you for the detailed explanation!

I'm going to close this now.
